# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec8ad2b9f9529e6d4f6ee8d6fffd46b04578de52e3c0a8fa6d69e726f01400a7a2ea33a2b321d9c176e1d80d247a0eb0b1139eabba6ead5109fcf4cb89ffb5d8

test:
  secret_key_base: 9d71225bc531917b24a62b087923a8704b9ecfed5471396a0e87de69d640410d7019f946bb01a33db81e7da0963c796338573dc9c092b0788859852705319bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
